Make ocd-restore do the git-pull.

diff --git a/bin/ocd-restore b/bin/ocd-restore
--- a/bin/ocd-restore
+++ b/bin/ocd-restore
@@ -7,11 +7,15 @@ IGNORE_RE="^\./(README$|\.git)"
 
 for ocddir in $OCDDIRS; do
 
-  echo -n "$ocddir: "
   if [ ! -d "$ocddir" ]; then
-    echo "doesn't exist!" && continue
+    echo "$ocddir: doesn't exist!" && continue
   fi
   cd $ocddir
+  echo "$ocddir: git-pull:"
+  git pull || {
+    echo "error: couldn't git-pull; check status in $ocddir" 1>&2
+    exit
+  }
 
   files=$(find . -type f | egrep -v  "$IGNORE_RE")
   dirs=$(find . -type d | egrep -v  "$IGNORE_RE")
@@ -20,6 +24,7 @@ for ocddir in $OCDDIRS; do
     mkdir -p $HOME/$dir
   done
 
+  echo -n "$ocddir: restoring"
   for file in $files; do
     echo -n .
     src="$file"
@@ -29,13 +34,13 @@ for ocddir in $OCDDIRS; do
     fi
     cp --preserve=mode $file $dst
   done
+  echo
 
   # Some changes require cleanup that OCD won't handle; e.g., if you rename
   # a file the old file will remain. Housekeeping commands that need to be
   # run may be put in $ocddir/.ocd_cleanup; they run only once.
   if ! cmp $HOME/.ocd_cleanup{,_ran} &>/dev/null; then
-    echo -e "\nrunning: $HOME/.ocd_cleanup"
+    echo -e "\n$ocddir: running $HOME/.ocd_cleanup:"
     $HOME/.ocd_cleanup && cp $HOME/.ocd_cleanup{,_ran}
   fi
-  echo
 done
