Minor change.

diff --git a/.config/openbox/pipemenus/displays b/.config/openbox/pipemenus/displays
--- a/.config/openbox/pipemenus/displays
+++ b/.config/openbox/pipemenus/displays
@@ -2,20 +2,22 @@
 
 echo "<openbox_pipe_menu>"
 
-which xrandr 1>/dev/null || {
-  echo '<item label="Error: xrandr is not installed">'
+function endexit {
   echo '</openbox_pipe_menu>'
   exit
+}
+
+which xrandr 1>/dev/null || {
+  echo '<item label="Error: xrandr is not installed">'
+  endexit
 }
 
 displays=$(xrandr -q | egrep ' (connected|disconnected) ' | awk '{print $1}')
 
 if [ -z "$displays" ]; then
   echo '<item label="Error: xrandr reports no displays.">'
-  echo '</openbox_pipe_menu>'
-  exit
+  endexit
 fi
-
 
 for display in $displays; do
   echo "<item label=\"$display\"><action name=\"Execute\"><execute>"
@@ -38,5 +40,4 @@ cat << END
 </item>
 END
 
-
-echo "</openbox_pipe_menu>"
+endexit
